networks:
  noblestride-network:
    external: true

services:
  api:
    build: .
    container_name: recommender_api
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${API_DB_HOST}
    volumes:
      - .:/app  # optional: enables hot reload for dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - noblestride-network

 

  airflow:
    build:
      context: ./airflow-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      - PYTHONUNBUFFERED=1
      - AIRFLOW_CONN_AIRFLOW_DB=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
    volumes:
      - ./airflow-orchestrator/dags:/usr/local/airflow/dags
      - ./airflow-orchestrator/plugins:/usr/local/airflow/plugins
      - ./airflow-orchestrator/requirements.txt:/usr/local/airflow/requirements.txt
      - ./airflow-orchestrator/packages.txt:/usr/local/airflow/packages.txt
 
    entrypoint: bash
    command: >
      -c "export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH && \
      sleep 10 && \
      airflow db init && \
      airflow roles create Admin && \
      airflow users create -u admin -f admin -l user -r Admin -e admin@example.com -p admin &&\
      airflow webserver
      "    networks:
      - noblestride-network

volumes:
  pgdata: