networks:
  noblestride-network:
    external: true

services:
  api:
    build: .
    container_name: recommender_api
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${API_DB_HOST}
    volumes:
      - .:/app  # optional: enables hot reload for dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - noblestride-network

 

  airflow:
    build:
      context: ./airflow-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./airflow-orchestrator/dags:/usr/local/airflow/dags
      - ./airflow-orchestrator/plugins:/usr/local/airflow/plugins
      - ./airflow-orchestrator/requirements.txt:/usr/local/airflow/requirements.txt
      - ./airflow-orchestrator/packages.txt:/usr/local/airflow/packages.txt
 
    command: >
      bash -c "
      echo "PATH: $PATH" && \
      ls -l /usr/local/bin && \
      ls -l /usr/bin && \
      sleep 10 && \
      airflow db init && \
      airflow roles create Admin && \
      airflow users create -u admin -f admin -l user -r Admin -e admin@example.com -p admin &&\
      airflow webserver
      "
    networks:
      - noblestride-network

volumes:
  pgdata: