version: '3.8'

networks:
  noblestride-network:
    external: true

services:
  # 🚀 FastAPI app
  api:
    build: .
    container_name: recommender_api
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${API_DB_HOST}
    volumes:
      - .:/app  # Enables hot reload for dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - noblestride-network

  # 🌐 Airflow Webserver
  airflow-webserver:
    build:
      context: ./airflow-orchestrator
      dockerfile: Dockerfile
    container_name: airflow_webserver
    ports:
      - "8090:8080"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      - AIRFLOW_CONN_AIRFLOW_DB=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
    volumes:
      - ./airflow-orchestrator/dags:/opt/airflow/dags
      - ./airflow-orchestrator/plugins:/usr/local/airflow/plugins
      - ./airflow-orchestrator/requirements.txt:/usr/local/airflow/requirements.txt
      - ./airflow-orchestrator/packages.txt:/usr/local/airflow/packages.txt
    entrypoint: /entrypoint.sh
    command: airflow webserver
    depends_on:
      - airflow-scheduler
    networks:
      - noblestride-network

  # ⏰ Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./airflow-orchestrator
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
    volumes:
      - ./airflow-orchestrator/dags:/opt/airflow/dags
      - ./airflow-orchestrator/plugins:/usr/local/airflow/plugins
      - ./airflow-orchestrator/requirements.txt:/usr/local/airflow/requirements.txt
      - ./airflow-orchestrator/packages.txt:/usr/local/airflow/packages.txt
    entrypoint: /entrypoint.sh
    command: airflow scheduler
    networks:
      - noblestride-network

volumes:
  pgdata:
