services:
  api:
    build: .
    container_name: recommender_api
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  # optional: enables hot reload for dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: recommender_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./airflow-orchestrator/dags:/usr/local/airflow/dags
      - ./airflow-orchestrator/plugins:/usr/local/airflow/plugins
      - ./airflow-orchestrator/requirements.txt:/usr/local/airflow/requirements.txt
      - ./airflow-orchestrator/packages.txt:/usr/local/airflow/packages.txt
      - ./airflow-orchestrator/.astro:/usr/local/airflow/.astro
    command: >
      bash -c "
        pip install --no-cache-dir astro &&
        astro dev start
      "

volumes:
  pgdata: